apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: launchsin-api
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-staging.launchsin.com
    secretName: api-staging-tls
  rules:
  - host: api-staging.launchsin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: launchsin-api
            port:
              number: 80
